# Generated by Django 5.1.6 on 2025-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulbStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('brightness', models.IntegerField()),
                ('color_temp', models.IntegerField()),
                ('red_temp', models.IntegerField()),
                ('green_temp', models.IntegerField()),
                ('blue_temp', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bulb Statusses',
            },
        ),
        migrations.CreateModel(
            name='CurtainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('open_percent', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Curtain Statusses',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_secret_key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('connected', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Bulb'), (2, 'Plug'), (3, 'Thermostat'), (4, 'Curtain'), (5, 'Weather Station'), (6, 'Lawn Mower')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawnMowerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('battery_percent', models.IntegerField(default=100)),
                ('cutting_mode', models.CharField(max_length=50)),
                ('cutting_height_mm', models.IntegerField()),
                ('current_area_m2', models.IntegerField()),
                ('total_cutting_time_minutes', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Lawn Mower Statusses',
            },
        ),
        migrations.CreateModel(
            name='PlugStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('current_power_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_energy_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Plug Statusses',
            },
        ),
        migrations.CreateModel(
            name='ThermostatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('target_temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Thermostat Statusses',
            },
        ),
        migrations.CreateModel(
            name='WeatherStationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_percent', models.IntegerField(default=0)),
                ('pressure_hpa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('wind_speed_kmh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Weather Station Statusses',
            },
        ),
    ]
