# Generated by Django 5.1.6 on 2025-03-23 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_secret_key", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=100, null=True)),
                ("model", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("power", models.BooleanField(default=False)),
                ("connected", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Bulb"),
                            (2, "Plug"),
                            (3, "Thermostat"),
                            (4, "Curtain"),
                            (5, "Weather Station"),
                            (6, "Lawn Mower"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bulb",
            fields=[
                (
                    "basedevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="devices.basedevice",
                    ),
                ),
                ("brightness", models.IntegerField(default=100)),
                ("color_temp", models.IntegerField(default=2700)),
                ("red_temp", models.IntegerField(default=255)),
                ("green_temp", models.IntegerField(default=255)),
                ("blue_temp", models.IntegerField(default=255)),
            ],
            options={
                "verbose_name_plural": "Bulbs",
            },
            bases=("devices.basedevice",),
        ),
        migrations.CreateModel(
            name="Curtain",
            fields=[
                (
                    "basedevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="devices.basedevice",
                    ),
                ),
                ("position", models.IntegerField()),
                ("open_percent", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Curtains",
            },
            bases=("devices.basedevice",),
        ),
        migrations.CreateModel(
            name="LawnMower",
            fields=[
                (
                    "basedevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="devices.basedevice",
                    ),
                ),
                ("battery_percent", models.IntegerField(default=100)),
                ("cutting_mode", models.CharField(max_length=50)),
                ("cutting_height_mm", models.IntegerField()),
                ("current_area_m2", models.IntegerField()),
                ("total_cutting_time_minutes", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Lawn Mowers",
            },
            bases=("devices.basedevice",),
        ),
        migrations.CreateModel(
            name="Plug",
            fields=[
                (
                    "basedevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="devices.basedevice",
                    ),
                ),
                (
                    "current_power_w",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_energy_kwh",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "verbose_name_plural": "Plugs",
            },
            bases=("devices.basedevice",),
        ),
        migrations.CreateModel(
            name="Thermostat",
            fields=[
                (
                    "basedevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="devices.basedevice",
                    ),
                ),
                (
                    "target_temperature",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_temperature",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("humidity", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Thermostats",
            },
            bases=("devices.basedevice",),
        ),
        migrations.CreateModel(
            name="WeatherStation",
            fields=[
                (
                    "basedevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="devices.basedevice",
                    ),
                ),
                ("temperature_c", models.DecimalField(decimal_places=2, max_digits=5)),
                ("humidity_percent", models.IntegerField(default=0)),
                ("pressure_hpa", models.DecimalField(decimal_places=2, max_digits=7)),
                ("wind_speed_kmh", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rainfall", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name_plural": "Weather Stations",
            },
            bases=("devices.basedevice",),
        ),
    ]
