# Generated by Django 5.1.5 on 2025-01-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
