# Generated by Django 5.1.6 on 2025-03-23 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_basedevice_device_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulb",
            name="blue_temp",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(255),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="bulb",
            name="brightness",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="bulb",
            name="color_temp",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bulb",
            name="green_temp",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(255),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="bulb",
            name="red_temp",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(255),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="curtain",
            name="open_percent",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="lawnmower",
            name="battery_percent",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lawnmower",
            name="current_area_m2",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="lawnmower",
            name="cutting_height_mm",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="lawnmower",
            name="total_cutting_time_minutes",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="thermostat",
            name="humidity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
