# Generated by Django 5.2 on 2025-04-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_bulb_blue_temp_alter_bulb_brightness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedevice',
            name='location',
            field=models.CharField(choices=[('LIVING ROOM', 'Living Room'), ('KITCHEN', 'Kitchen'), ('HALLWAY', 'Hallway'), ('BEDROOM', 'Bedroom'), ('BATHROOM', 'Bathroom'), ('GARDEN', 'Garden'), ('BACKYARD', 'Backyard')], max_length=50),
        ),
        migrations.CreateModel(
            name='DeviceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Bulb'), (2, 'Plug'), (3, 'Thermostat'), (4, 'Curtain'), (5, 'Weather Station'), (6, 'Lawn Mower')])),
                ('location', models.CharField(choices=[('LIVING ROOM', 'Living Room'), ('KITCHEN', 'Kitchen'), ('HALLWAY', 'Hallway'), ('BEDROOM', 'Bedroom'), ('BATHROOM', 'Bathroom'), ('GARDEN', 'Garden'), ('BACKYARD', 'Backyard')])),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype')),
            ],
        ),
    ]
