# Generated by Django 5.1.5 on 2025-01-31 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_delete_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_secret_key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type_id', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('connected', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
