# Generated by Django 5.2 on 2025-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_basedevice_location_deviceschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deviceschedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='deviceschedule',
            name='name',
        ),
        migrations.AlterField(
            model_name='deviceschedule',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
