# Generated by Django 5.1.5 on 2025-01-31 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulbStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('brightness', models.CharField(max_length=100)),
                ('color_temp', models.CharField(max_length=10)),
                ('red_temp', models.CharField(max_length=10)),
                ('green_temp', models.CharField(max_length=10)),
                ('blue_temp', models.CharField(max_length=10)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
