# Generated by Django 5.1.7 on 2025-04-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_basedevice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulb',
            name='blue_temp',
        ),
        migrations.RemoveField(
            model_name='bulb',
            name='green_temp',
        ),
        migrations.RemoveField(
            model_name='bulb',
            name='red_temp',
        ),
        migrations.AddField(
            model_name='bulb',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
