# Generated by Django 5.2 on 2025-04-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_deviceschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceschedule',
            name='custom_device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceschedule',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deviceschedule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.basedevice'),
        ),
    ]
