# Generated by Django 5.1.5 on 2025-01-31 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_bulbstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulbstatus',
            options={'verbose_name_plural': 'Bulb Statusses'},
        ),
        migrations.CreateModel(
            name='PlugStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('current_power_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_energy_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name_plural': 'Bulb Statusses',
            },
        ),
    ]
