# Generated by Django 5.1.5 on 2025-01-31 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_bulbstatus_options_plugstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugstatus',
            options={'verbose_name_plural': 'Plug Statusses'},
        ),
        migrations.CreateModel(
            name='ThermostatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('target_temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.CharField(max_length=10)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name_plural': 'Thermostat Statusses',
            },
        ),
    ]
