# Generated by Django 5.1.5 on 2025-01-31 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_plugstatus_options_thermostatstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulbstatus',
            name='blue_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bulbstatus',
            name='brightness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bulbstatus',
            name='color_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bulbstatus',
            name='green_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bulbstatus',
            name='red_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='type_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thermostatstatus',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CurtainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('open_percent', models.IntegerField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name_plural': 'Curtain Statusses',
            },
        ),
    ]
