# Generated by Django 5.1.5 on 2025-01-31 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_bulbstatus_blue_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure_hpa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('wind_speed_kmh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=5)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name_plural': 'Weather Station Statusses',
            },
        ),
    ]
