# Generated by Django 5.1.5 on 2025-01-31 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_weatherstationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawnMowerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=10)),
                ('battery_percent', models.IntegerField()),
                ('cutting_mode', models.CharField(max_length=50)),
                ('cutting_height_mm', models.IntegerField()),
                ('current_area_m2', models.IntegerField()),
                ('total_cutting_time_minutes', models.IntegerField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name_plural': 'Lawn Mower Statusses',
            },
        ),
    ]
