# Generated by Django 5.1.6 on 2025-02-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_lawnmowerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstationstatus',
            name='humidity_percent',
            field=models.IntegerField(default=0),
        ),
    ]
