# Generated by Django 5.1.6 on 2025-02-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_weatherstationstatus_humidity_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawnmowerstatus',
            name='battery_percent',
            field=models.IntegerField(default=100),
        ),
    ]
